[v4r4] use BaseRequestHandler for FileCatalog
DIRACGrid/WebAppDIRAC pull request #541
Opened 2021-09-13 12:22 UTC by TaykYoku

BEGINRELEASENOTES

Use WebHandler with DIRAC.Core.Tornado.Server.privat.BaseRequestHandler for FileCatalog handler.

CHANGE: Use WebHandler with DIRAC.Core.Tornado.Server.privat.BaseRequestHandler for FileCatalog handler.

 ENDRELEASENOTES

2022-03-04 10:50 UTC, andresailer requested changes
Mostly "syntactic sugar", but the one about `path=None` needs change or clarification.

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +        for key in result:
why not `items()` any more?

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            for lfn in path.split(","):
add protection in case `path=None`

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            for key in dirmeta:
why not `items()`? value was used

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
>          if len(dirmeta) > 0:
this is can be dropped, the loop over empty dict will be fine.

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            size = value["Size"] if "Size" in value else ""
```suggestion
            size = value.get("Size", "")
```

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            date = str(value["CreationDate"]) if "CreationDate" in value else ""
```suggestion
            date = str(value.get("CreationDate", ""))
```

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
>          if len(filemeta) > 0:
`if` could be dropped

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            return {"success": "false", "error": "Metadata query error: %s" % repr(e)}
```suggestion
            return {"success": "false", "error": f"Metadata query error: {e!r}"}
```

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +            gLogger.error("request: %s" % result["Message"])
```suggestion
            gLogger.error("request:", result["Message"])
```

2022-03-04 10:50 UTC, andresailer commented on src/WebAppDIRAC/WebApp/handler/FileCatalogHandler.py
> +        if len(result["Value"]) > 0:
if `result["Value"]` is a list (dict?) then the list comprehension also works with an empty `result["Value"]`?

2022-03-07 14:13 UTC, fstagni commented
@andresailer I think I addressed all

2022-03-07 15:27 UTC, andresailer approved these changes

2022-03-07 16:00 UTC, merged